### ISSUE TITLE
[2024.8.3] cctbx test suite is not compatible with Python3.12

### ISSUE THREAD

**Issue by picca** [cctbx/cctbx_project#1018]
Hello, while preparing the next Debian package of cctbx, I got this error.

```
libtbx.python "/usr/lib/python3/dist-packages/libtbx/tst_easy_mp.py" [FAIL] 4.2s
  Time:  4.19
  Return code: 1
  OKs: 0
  Standard error:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/libtbx/tst_easy_mp.py", line 224, in <module>
        run(args=sys.argv[1:])
      File "/usr/lib/python3/dist-packages/libtbx/tst_easy_mp.py", line 220, in run
        exercise(exercise_fail)
      File "/usr/lib/python3/dist-packages/libtbx/tst_easy_mp.py", line 98, in exercise
        from libtbx.clear_paths import \
      File "/usr/lib/python3/dist-packages/libtbx/clear_paths.py", line 2, in <module>
        from distutils.dir_util import remove_tree
    ModuleNotFoundError: No module named 'distutils'

Please verify these tests manually.

Summary:
  Tests run                    : 552
  Failures                     : 1
  Warnings (possible failures) : 0
  Known Failures (  4)         : 3
  Known Unstable (  3)         : 0
  Stderr output (discouraged)  : 8

See run_tests_parallel_zlog for full output.
```

Indeed distutils is no more available.

Cheers

Fred

**Comment by picca** [comment]
what about using shutil.rmtree instead ?

**Comment by bkpoon** [comment]
Thanks for letting us know. We are running nightly tests on Python 3.12. I guess our conda environment pulls in something that provides `distutils`.

I'll work on removing `distutils` imports for the next release (coming soon).
