### ISSUE TITLE
xtriage fail on loggraph

### ISSUE THREAD

**Issue by frankvm04** [cctbx/cctbx_project#1031]
Calling xtriage with `scaling.input.parameters.reporting.loggraphs=True` fails. Looks identical to issue #970 
I swear I don't sit here and test this one command hourly, but we do use it in our automated analysis runs. 

```bash
Traceback (most recent call last):
  File "/opt/sbgrid/i386-mac/phenix/1.21.1-5286/phenix-1.21.1-5286/build/../modules/cctbx_project/mmtbx/command_line/xtriage.py", line 9, in <module>
    xtriage.run(args=sys.argv[1:])
  File "/opt/sbgrid/i386-mac/phenix/1.21.1-5286/phenix-1.21.1-5286/modules/cctbx_project/mmtbx/scaling/xtriage.py", line 1397, in run
    xtriage_results.show(out=graph_out)
  File "/opt/sbgrid/i386-mac/phenix/1.21.1-5286/phenix-1.21.1-5286/modules/cctbx_project/mmtbx/scaling/__init__.py", line 236, in show
    self._show_impl(out=out)
  File "/opt/sbgrid/i386-mac/phenix/1.21.1-5286/phenix-1.21.1-5286/modules/cctbx_project/mmtbx/scaling/xtriage.py", line 852, in _show_impl
    self.data_strength_and_completeness.show(out)
  File "/opt/sbgrid/i386-mac/phenix/1.21.1-5286/phenix-1.21.1-5286/modules/cctbx_project/mmtbx/scaling/__init__.py", line 236, in show
    self._show_impl(out=out)
  File "/opt/sbgrid/i386-mac/phenix/1.21.1-5286/phenix-1.21.1-5286/modules/cctbx_project/mmtbx/scaling/data_statistics.py", line 827, in _show_impl
    self.data_strength.show(out)
  File "/opt/sbgrid/i386-mac/phenix/1.21.1-5286/phenix-1.21.1-5286/modules/cctbx_project/mmtbx/scaling/__init__.py", line 236, in show
    self._show_impl(out=out)
  File "/opt/sbgrid/i386-mac/phenix/1.21.1-5286/phenix-1.21.1-5286/modules/cctbx_project/mmtbx/scaling/data_statistics.py", line 117, in _show_impl
    out.show_plot(self.table)
  File "/opt/sbgrid/i386-mac/phenix/1.21.1-5286/phenix-1.21.1-5286/modules/cctbx_project/mmtbx/scaling/__init__.py", line 217, in show_plot
    print("", file=self.out)
ValueError: I/O operation on closed file
```

**Comment by bkpoon** [comment]
Sorry, it is the same bug. I fixed it in the nightly builds, but I did not propagate it into the point releases. Can you try a nightly build from SBGrid? We are also in the process of getting the next release ready, so the fix will definitely be in the next release.

**Comment by frankvm04** [comment]
I'll give it a try (but sure it will work) Thanks
