### ISSUE TITLE
mask use in image viewer does not work (missing import?)

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/cctbx_project#107]
```
Graemes-MacBook-Pro-5:images graeme$ dials.find_spots datablock.json nproc=8 spotfinder.filter.d_min=2.2
Sorry: Unable to handle the following arguments:
  datablock.json failed during DataBlock processing:
    Traceback (most recent call last):
      File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 310, in try_read_datablocks
        self.datablocks.append(converter.from_string(argument))
      File "/Users/graeme/svn/cctbx/modules/dials/util/phil.py", line 47, in from_string
        check_format=self._check_format))
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 986, in from_json_file
        return DataBlockFactory.from_json(infile.read(), check_format)
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 976, in from_json
        check_format)
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 964, in from_dict
        importer = DataBlockDictImporter(obj, check_format)
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 668, in __init__
        self.datablocks = self._load_datablocks(obj, check_format)
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 683, in _load_datablocks
        return [self._load_datablocks(dd, check_format) for dd in obj]
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 832, in _load_datablocks
        iset.external_lookup.mask.data = ImageMask(pickle.load(infile))
    NameError: global name 'ImageMask' is not defined
```

**Comment by rjgildea** [comment]
Introduced in: https://github.com/cctbx/cctbx_project/commit/f0f325035358a2d5d356147968b866c7ebe0301b#diff-27ab99ef070532f8198b944cd678aefaR778

By comparison with nearby changes in that diff, I suspect "ImageMask" is supposed to be "ImageBool".

**Comment by graeme-winter** [comment]
Computer says yes

Tests needed here methinks…

**Comment by rjgildea** [comment]
Does running dials.export_bitmaps with a mask set hit that line of code?
