### ISSUE TITLE
cctbx.maptbx.tst_interpolation failing

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#137]
cctbx.maptbx.tst_interpolation (from libtbx.run_tests_parallel)
Failing for the past 6 builds (Since Unstable#5969 )

**Stacktrace**
```
Traceback (most recent call last):
  File "/scratch/jenkins_slave/workspace/cctbx_tests/build_dials/modules/cctbx_project/cctbx/maptbx/tst_interpolation.py", line 128, in <module>
    exercise(f = f, gx = gx, gy = gy, gz = gz, function_type=function_type)
  File "/scratch/jenkins_slave/workspace/cctbx_tests/build_dials/modules/cctbx_project/cctbx/maptbx/tst_interpolation.py", line 111, in exercise
    if(abs(tl)>eps and abs(tt)>eps): assert tl >=tt
AssertionError
```

**Standard Output**
```
- using: f=3*(x-5)**1-2*(y-5)**1+6*(z-5)**1, gx=3*(x-5)**0, gy=-2*(y-5)**0, gz=6*(z-5)**0
 Step                   Linear                                         Quadratic                              Tricubic
0.400 (  0.000000   0.000000   0.000000   0.000000) (  0.000000   0.000000   0.000000   0.000000) (  0.000000   0.000000   0.000000   0.000000)
0.200 (  0.000000   0.000000   0.000000   0.000000) (  0.000000   0.000000   0.000000   0.000000) (  0.000000   0.000000   0.000000   0.000000)
0.100 (  0.000000   0.000000   0.000000   0.000000) (  0.000000   0.000000   0.000000   0.000000) (  0.000000   0.000000   0.000000   0.000000)

- using: f=3*(x-5)**2-2*(y-5)**2+6*(z-5)**2, gx=6*(x-5)**1, gy=-4*(y-5)**1, gz=12*(z-5)**1
 Step                   Linear                                         Quadratic                              Tricubic
0.400 (  0.856039   4.760145   2.679838   3.411309) (  0.000000   0.000000   0.000000   0.000000) (  0.000000   0.000000   0.000000   0.000000)
0.200 (  0.276233   1.999026   1.117664   1.540115) (  0.000000   0.000000   0.000000   0.000000) (  0.000000   0.000000   0.000000   0.000000)
0.100 (  0.000000   1.651198   2.231536   2.006509) (  0.000000   0.000000   0.000000   0.000000) (  0.000000   0.000000   0.000000   0.000000)

- using: f=3*(x-5)**3-2*(y-5)**3+6*(z-5)**3, gx=9*(x-5)**2, gy=-6*(y-5)**2, gz=18*(z-5)**2
 Step                   Linear                                         Quadratic                              Tricubic
0.400 (  2.586309   7.620262   9.261287  12.991029) (  0.313005   7.110667   3.734795   9.372943) (  0.000000   0.000000   0.000000   0.000000)
0.200 (  0.266802   5.631061   2.414491   6.323487) (  0.105294   1.461357   0.609767   1.643325) (  0.000000   0.000000   0.000000   0.000000)
0.100 (  0.000000   3.034974   4.512302   5.256095) (  0.000000   0.251886   0.690959   1.164368) (  0.000000   0.000000   0.000000   0.000000)

- using: f=3*(x-5)**4-2*(y-5)**4+6*(z-5)**4, gx=12*(x-5)**3, gy=-8*(y-5)**3, gz=24*(z-5)**3
 Step                   Linear                                         Quadratic                              Tricubic
0.400 (  2.094534  21.266381  10.176083  19.152151) (  0.854878  42.381334  22.817590  27.257790) (  0.147800  39.721959  20.093914  24.201829)
0.200 (  3.513326   4.400937   6.602785   8.525561) (  1.656211   2.719456   2.009242   4.993828) (  3.586017   0.020070   0.664298   0.672387)
```

**Comment by Anthchirp** [comment]
937d4eac33ff9859232c6347ee5e67d1951cec0f seems to have done the trick.
