### ISSUE TITLE
Prime/scitbx: scitbx exception in image scaling and parrallel_map

### ISSUE THREAD

**Issue by MVAppleby** [cctbx/cctbx_project#152]
Following recent commits to prime the following error occurs on previously merge-able datasets

```
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20180316/build/../modules/cctbx_project/prime/command_line/run.py", line 21, in <module>
    prime.command_line.postrefine.run(sys.argv[1:])
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20180316/modules/cctbx_project/prime/command_line/postrefine.py", line 166, in run
    scaled_pres_set = scale_frames(frames, frame_files, iparams)
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20180316/modules/cctbx_project/prime/command_line/postrefine.py", line 65, in scale_frames
    processes=iparams.n_processors)
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20180316/modules/cctbx_project/libtbx/easy_mp.py", line 627, in parallel_map
    result = res()
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20180316/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20180316/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 115, in __call__
    self.raise_handler( exception = exception )
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20180316/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 145, in raise_with_stacktrace
    self.stacktrace( exception = exception )
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20180316/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 86, in __call__
    raise exception
RuntimeError: scitbx Internal Error: /dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20180316/modules/cctbx_project/scitbx/math/basic_statistics.h(173): SCITBX_ASSERT(data.size()) failure.
```

**Comment by MVAppleby** [comment]
Bug fix for reflection rejection  in prime now causes some previously mergable data to fail as the default sigma_reflection is low (3.0)

To solve this use: prime.run prime.phil sigma_rejection=x and set x to a higher value i.e. 10 or 99.
