### ISSUE TITLE
iotbx.merging_statistics crashing with empty bins

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#17]
Think small molecule world with small unit cells, few reflections, and high resolution:
```
>>> import iotbx.merging_statistics as ims
>>> ims.dataset_statistics(i_obs=ims.select_data('/dls/mx-scratch/dials/cctbx-issue-17/AUTOMATIC_DEFAULT_scaled_unmerged.mtz', data_labels=None), n_bins=20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/wra62962/files/dials/modules/cctbx_project/iotbx/merging_statistics.py", line 540, in __init__
    cc_one_half_method=cc_one_half_method)
  File "/scratch/wra62962/files/dials/modules/cctbx_project/iotbx/merging_statistics.py", line 239, in __init__
    "(%g - %g)") % (self.d_max, self.d_min))
RuntimeError: No reflections within specified resolution range (0.965792 - 0.940519)
```

**Comment by Anthchirp** [comment]
code leading to error is
```
    n_expected = len(complete_set.indices())
    if (n_expected == 0) :
      raise RuntimeError(("No reflections within specified resolution range "+
        "(%g - %g)") % (self.d_max, self.d_min))
    self.completeness = min(self.n_uniq / n_expected, 1.)
```

**Comment by rjgildea** [comment]
binning_method = 'counting_sorted' possibly more useful/meaningful when not many reflections present?
