### ISSUE TITLE
Install only libtbx.easy_mp

### ISSUE THREAD

**Issue by sarahbuzz** [cctbx/cctbx_project#180]
Hello,

I'm interested in integrating the `libtbx.easy_mp` module into a code I'm writing to parallel on an SGE cluster. I'm attempting to install the entire project (`python boostrap.py`) but I get a `RuntimeError` when `Xrender` is installing:

`Installing Xrender...
  log file is /home/sbusby/Downloads/cctbx/base_tmp/Xrender_install_log
  getting package libXrender-0.9.7.tar.gz...
    downloading from http://cci.lbl.gov/cctbx_dependencies : 348.9 kB
    [0%.........20%.........40%.........60%.........80%.........100%]
  installing libXrender-0.9.7.tar.gz...
Traceback (most recent call last):
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1636, in <module>
    installer(args=sys.argv, log=sys.stdout)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 247, in __init__
    self.build_dependencies(packages=packages)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 759, in build_dependencies
    getattr(self, 'build_%s'%i)()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1337, in build_render
    self.build_compiled_package_simple(pkg_name=pkg, pkg_name_label=name)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 576, in build_compiled_package_simple
    self.configure_and_build(config_args=config_args, log=pkg_log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 557, in configure_and_build
    self.call("./%s %s" % (configure, " ".join(list(config_args))), log=log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 345, in call
    return call(args, log=log, verbose=self.verbose, **kwargs)
  File "/home/sbusby/Downloads/cctbx/modules/cctbx_project/libtbx/auto_build/installer_utils.py", line 53, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to './configure --prefix="/home/sbusby/Downloads/cctbx/base"' failed with exit code 1
Process failed with return code 1`

I don't need all the extra modules provided in CCTBX. Is there a way to just install/use the `libtbx.easy_mp` package?

I'm on a Debian OS (jessie).

**Comment by bkpoon** [comment]
Hi,

You're probably just missing the Xorg server development files. I think the
package is called xorg-dev on Debian.

As an alternative, you can download a binary installation from
http://cci.lbl.gov/cctbx_build/dev-1380/ and use libtbx.easy_mp from that
installation. The CentOS 6 build should work with Jessie.

--
Billy K. Poon
Research Scientist, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
1 Cyclotron Road, M/S 33R0345
Berkeley, CA 94720
Tel: (510) 486-5709
Fax: (510) 486-5909
Web: https://phenix-online.org

**Comment by nwmoriarty** [comment]
@sarahbuzz Have you solved your issue?
