### ISSUE TITLE
phenix.map_value_at_point (or eight_point_interpolation) does not work with ccp4 maps

### ISSUE THREAD

**Issue by biochem-fan** [cctbx/cctbx_project#19]
As discussed  more than one year ago in http://phenix-online.org/pipermail/cctbxbb/2015-December/001181.html, `phenix.map_value_at_point` (or `eight_point_interpolation` in `maptbx`) does not work with CCP4 (MRC) maps from `phenix.maps`.
```
$ phenix.fetch_pdb --mtz 3eml
$ phenix.maps 3eml.pdb 3eml-sf.cif

# Just to use the latest svn version
$ phenix.map_value_at_point 3eml_2mFo-DFc_map.ccp4 point="1.0 2.0 3.0"
Default params::

  label = None
  point = None
  resolution_factor = 0.25
  scale = *sigma volume
  resolution = None
  low_resolution = None

Map values at specified points:
Traceback (most recent call last):
  File "/misc/home/app/phenix-1.11.1-2575/build/../modules/cctbx_project/mmtbx/command_line/map_value_at_point.py", line 162, in <module>
    run(sys.argv[1:])
  File "/misc/home/app/phenix-1.11.1-2575/build/../modules/cctbx_project/mmtbx/command_line/map_value_at_point.py", line 146, in run
    "%10.3f"%map_3d.eight_point_interpolation(point_frac)).strip()
Boost.Python.ArgumentError: Python argument types in
    cctbx_maptbx_ext.eight_point_interpolation(double, tuple)
did not match C++ signature:
    eight_point_interpolation(scitbx::af::const_ref<double, scitbx::af::c_grid_padded<3ul, unsigned long> >, scitbx::vec3<double>)
```

However, it does work with maps generated by FFT in CCP4.
```
$ fft hklin 3eml_map_coeffs.mtz mapout fft.ccp4 <<EOF
LABIN F1=2FOFCWT PHI=PH2FOFCWT
END
EOF

$ phenix.map_value_at_point fft.ccp4 point="1.0 2.0 3.0"
Default params::

  label = None
  point = None
  resolution_factor = 0.25
  scale = *sigma volume
  resolution = None
  low_resolution = None

Map values at specified points:
  Input point: (1.000,2.000,3.000) Fractionalized: (0.034,0.026,0.035) Map value: -0.009

All done.
```

**Comment by keitaroyam** [comment]
CCP4 map file generated by phenix.maps seems to have grid around the coordinates of given molecules. Thus, it does not always cover whole asymmetric unit and does not allow interpolation at arbitrary point.

So in this case phenix.map_value_at_point should show error message properly or give value if the point is in the map file?
