### ISSUE TITLE
easy_run timeout test unstable

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#227]
```
1 tests failed.
FAILED:  libtbx.tst_fully_buffered_timeout

Error Message:
AssertionError

Stack Trace:
Traceback (most recent call last):
  File "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/libtbx/tst_fully_buffered_timeout.py", line 20, in 
    exercise()
  File "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/libtbx/tst_fully_buffered_timeout.py", line 13, in exercise
    test_command("sleep 1", 2, 1)
  File "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/libtbx/tst_fully_buffered_timeout.py", line 10, in test_command
    assert approx_equal(t1-t0, expected_time, 0.1)
AssertionError
```

btw may want to consider using the pypi package [procrunner](https://pypi.org/project/procrunner/) which I built for exactly this purpose, and is already installed for the DIALS builder

**Comment by olegsobolev** [comment]
Thanks for pointing it out. I increased tolerance of the test. Please check if it helps on your system.
Re procrunner. I just tried it and found out that it does not do what we need to do - actually kill underlying process with all its children.

**Comment by Anthchirp** [comment]
I am always open to pull requests.
