### ISSUE TITLE
dxtbx ImageSet broken with unicode paths

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#234]
Input:
```python
from __future__ import absolute_import, division, print_function

import os
import dials_regression
template = unicode(os.path.join(dials_regression.__path__[0], 'centroid_test_data', 'centroid_####.cbf'))

from dxtbx.datablock import DataBlockTemplateImporter
importer = DataBlockTemplateImporter([template])
imageset = importer.datablocks[0].extract_imagesets()[0]
print(imageset.get_path(1))
```

Output:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    print(imageset.get_path(1))
TypeError: No registered converter was able to produce a C++ rvalue of type std:
:string from this Python object of type unicode
```

**Comment by graeme-winter** [comment]
Weird - this works fine if you cast it back to a string inside the __init__ method - even if template very non-string-like i.e. 

```
dials.python tst.py 🤬/th_8_2_####.cbf
```

is fine...

**Comment by ndevenish** [comment]
Sounds like boost just doesn't know how to pass unicode objects to C++ ::string - there isn't any automatic transformation. C++ doesn't know unicode, it just things the string is bytes, which is in this case the correct thing to do.

I seem to remember, though can't find a good source immediately, that treating filenames as unicode strings is something of an antipattern because you can't guarantee what the origin filesystem is doing/whether going back and forth from the original encoding is correct.

Casting to str is the same as encoding to ASCII:
```python
>>> str(u"something")
'something'
>>> u"something".encode("ascii")
'something'
```
Which will (probably) fall over if the string actually contains any non-ascii or unicode characters e.g.:
```python
>>> str(u"£something")
>>> u"£something".encode("ascii")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in position 0: ordinal not in range(128)
```
