### ISSUE TITLE
LZW move was not handled in the libtbx tests

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/cctbx_project#265]
```
libtbx.python "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/tst_lzw.py" [FAIL] 0.1s
  Time:  0.11
  Return code: 1
  OKs: 0
  Standard error:
    Traceback (most recent call last):
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/tst_lzw.py", line 19, in <module>
        run(args=sys.argv[1:])
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/tst_lzw.py", line 4, in run
        from libtbx import lzw
    ImportError: cannot import name lzw
```

**Comment by graeme-winter** [comment]
For reference the move commit was https://github.com/cctbx/cctbx_project/commit/161603069c5ddd44ad43f546fccbfb39374675ad
