### ISSUE TITLE
Cope with the idea that Eiger data files may not contain _data_ in name

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/cctbx_project#268]
```
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-12-2/build/../modules/cctbx_project/dxtbx/command_line/to_xds.py", line 39, in <module>
    run(sys.argv[1:])
  File "/dls_sw/apps/dials/dials-v1-12-2/build/../modules/cctbx_project/dxtbx/command_line/to_xds.py", line 36, in run
    xsx.XDS_INP()
  File "/dls_sw/apps/dials/dials-v1-12-2/modules/cctbx_project/dxtbx/serialize/xds.py", line 348, in XDS_INP
    assert g, 'No associated data files found for %s' % master_file
AssertionError: No associated data files found for /dls/mx-scratch/dials/i04-eiger/thaumatin/1/thaumatin_4_1_master.h5
```

@rjgildea has already handled something similar for xia2 in https://github.com/xia2/xia2/commit/5f1fbdea57c8c06aa026070c4d9981b0d768b3fe

**Comment by graeme-winter** [comment]
Resolved in https://github.com/cctbx/cctbx_project/commit/a875d6bd54b1cf8c4d28fe0bf96f7815265fa798
