### ISSUE TITLE
New iotbx errors

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/cctbx_project#277]
Manually edited the ccp4 monomer library to fix the 1,7 problem, now get:

```
Error: the following jobs returned non-zero exit codes or suspicious stderr output:

libtbx.python "/Users/graeme/svn/cctbx/modules/cctbx_project/iotbx/regression/tst_data_manager.py" [FAIL] 3.6s
  Time:  3.65
  Return code: 1
  OKs: 0
  Standard error:
    Sorry: Traceback (most recent call last):
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/mmtbx/monomer_library/pdb_interpretation.py", line 1488, in apply_mod
        mod_mon = self.monomer.apply_mod(mod_mod_id)
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/mmtbx/monomer_library/cif_types.py", line 429, in apply_mod
        result.delete_atom_in_place(mod_atom.atom_id)
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/mmtbx/monomer_library/cif_types.py", line 346, in delete_atom_in_place
        raise RuntimeError("delete_atom_in_place: unknown atom_id: %s" % atom_id)
    RuntimeError: delete_atom_in_place: unknown atom_id: HN1
    apply_mod failure:
      pdbres="ASN A   2 "
      comp id: ASN
      mod id: DEL-HN1
libtbx.python "/Users/graeme/svn/cctbx/modules/cctbx_project/iotbx/regression/tst_pdb_as_cif.py" [FAIL] 3.7s
  Time:  3.69
  Return code: 1
  OKs: 0
  Standard error:
    Sorry: Traceback (most recent call last):
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/mmtbx/monomer_library/pdb_interpretation.py", line 1488, in apply_mod
        mod_mon = self.monomer.apply_mod(mod_mod_id)
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/mmtbx/monomer_library/cif_types.py", line 429, in apply_mod
        result.delete_atom_in_place(mod_atom.atom_id)
      File "/Users/graeme/svn/cctbx/modules/cctbx_project/mmtbx/monomer_library/cif_types.py", line 346, in delete_atom_in_place
        raise RuntimeError("delete_atom_in_place: unknown atom_id: %s" % atom_id)
    RuntimeError: delete_atom_in_place: unknown atom_id: HN1
    apply_mod failure:
      pdbres="LEU A  44 "
      comp id: LEU
      mod id: DEL-HN1

Please verify these tests manually.

Summary:
  Tests run                    : 105
  Failures                     : 2
  Warnings (possible failures) : 0
  Stderr output (discouraged)  : 2

See run_tests_parallel_zlog for full output.


```

running

```
libtbx.run_tests_parallel module=iotbx nproc=8
```

are these tests known to work? Trying to get a clean baseline for https://github.com/cctbx/cctbx_project/pull/276 to give a tick for the merge, but it is impossible as the master has problems

**Comment by olegsobolev** [comment]
Hi Graeme,

These tests work in my hands.

Oleg.

**Comment by graeme-winter** [comment]
Are they dependent on working with the PHENIX monomer library rather than the CCP4 one?

If so, should probably add a check to reduce the noise? When I ran the mmtbx tests earlier I got > 100 errors...

**Comment by Anthchirp** [comment]
assume this is fixed with @rjgildea's commit
