### ISSUE TITLE
dxtbx filedescriptor leak

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#28]
```
from dxtbx.datablock import DataBlockFactory
db = DataBlockFactory.from_json_file('datablock.json')
```
leaks file descriptors. More details at xia2/xia2#117

**Comment by graeme-winter** [comment]
Looks like

```
--- a/dxtbx/format/FormatHDFEigerNearlyNexus.py
+++ b/dxtbx/format/FormatHDFEigerNearlyNexus.py
@@ -230,7 +230,9 @@ class EigerNXmxFixer(object):
     # Change relative paths to absolute paths
     for name in handle_orig['/entry/data'].iterkeys():
       del handle['entry/data'][name]
-      handle['entry/data'][name] = h5py.ExternalLink(handle_orig['entry/data'][name].file.filename, 'entry/data/data')
+      filename = handle_orig['entry/data'][name].file.filename
+      handle['entry/data'][name] = h5py.ExternalLink(filename, 'entry/data/data')
+      handle['entry/data']["_filename_" + name] = filename # Store file namesa
 

``` 

in 1a2e937bcbc2b3f5d0adf1c69724bc8373a2f4c2 a lot to do with this?

**Comment by jmp1985** [comment]
I've fixed this by changing the format class such that the models are constructed from the "fixed" master file but the data is accessed from the original handle (which is opened as read only).

**Comment by graeme-winter** [comment]
Not convinved @jmp1985 

```

[gw56@ws133 dials]$ dials.import ../thaumatin_low_dose_28turns/thaumatin_0.025trans_0.1dpf_4dps_master.h5
DIALS 1.dev.1318-g95bf872
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 734, in <module>
    halraiser(e)
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 732, in <module>
    script.run()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 596, in run
    params, options = self.parser.parse_args(show_diff_phil=False)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 782, in parse_args
    quick_parse=quick_parse)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 514, in parse_args
    format_kwargs=format_kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 208, in __init__
    format_kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 263, in try_read_datablocks_from_images
    format_kwargs=format_kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 899, in from_filenames
    format_kwargs=format_kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 472, in __init__
    format_kwargs=format_kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 642, in _create_single_file_imageset
    format_instance = format_class(abspath(filename), **format_kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/FormatHDFEigerNearlyNexus.py", line 268, in __init__
    FormatHDF5.__init__(self, image_file, **kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/FormatHDF5.py", line 16, in __init__
    Format.__init__(self, image_file, **kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/Format.py", line 119, in __init__
    self.setup()
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/Format.py", line 129, in setup
    self._start()
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/FormatHDFEigerNearlyNexus.py", line 311, in _start
    data = NXdata(fixer.handle_orig[data.handle.name])
UnboundLocalError: Please report this error to dials-support@lists.sourceforge.net: local variable 'data' referenced before assignment

```

**Comment by jmp1985** [comment]
Not sure why I commented out that bit but this seems to have been fixed.
