### ISSUE TITLE
Issues building cctbx base on mojave

### ISSUE THREAD

**Issue by rjgildea** [cctbx/cctbx_project#333]
Attempting to run bootstrap on a clean macOS Mojave installation it fails with the following error: 
```
$ python bootstrap.py --builder=dials --nproc=8 --git-ssh
...
zlib.h missing -- try running 'xcode-select --install' first
```

https://github.com/cctbx/cctbx_project/blob/7cbc03abf070a35d3bb06c119fa32ec652bb95d2/libtbx/auto_build/install_base_packages.py#L795

Contrary to what the error message suggests I have run `xcode-select --install`.

Note from  https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes:
> The Command Line Tools package installs the macOS system headers inside the macOS SDK. Software that compiles with the installed tools will search for headers within the macOS SDK provided by either Xcode at:
> 
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
> 
> or the Command Line Tools at:
> 
> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
> 
> depending on which is selected using xcode-select.
> 
> The command line tools will search the SDK for system headers by default. However, some software may fail to build correctly against the SDK and require macOS headers to be installed in the base system under /usr/include. If you are the maintainer of such software, we encourage you to update your project to work with the SDK or file a bug report for issues that are preventing you from doing so. As a workaround, an extra package is provided which will install the headers to the base system. In a future release, this package will no longer be provided. You can find this package at:
> 
> /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
> 
>  To make sure that you're using the intended version of the command line tools, run xcode-select -s <path to Xcode> or xcode select -s /Library/Developer/CommandLineTools after installing.

After installing /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg headers are now present in /usr/include/ and bootstrap proceeds as far as wxPython before failing:
```
Installing wxPython...
  log file is /Users/rjgildea/software/cctbx/base_tmp/wxPython_install_log
  getting package wxPython-src-3.0.2.0.tar.bz2...
    downloading from http://cci.lbl.gov/cctbx_dependencies : 55.6 MB
    [0%.........20%.........40%.........60%.........80%.........100%]
  installing wxPython-src-3.0.2.0.tar.bz2...
  patching src/osx/webview_webkit.mm
  patching src/osx/core/bitmap.cpp
  patching src/osx/carbon/dataobj.cpp
  building wxWidgets with options:
    --prefix="/Users/rjgildea/software/cctbx/base"
    --with-opengl
    --enable-unicode
    --without-libjbig
    --without-liblzma
    --with-libjpeg=builtin
    --enable-optimize
    --disable-debugreport
    --with-osx_cocoa
    --with-macosx-version-min=10.7
    --with-mac
    --enable-monolithic
    --disable-mediactrl
    CPPFLAGS="-D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1 -mmacosx-version-min=10.7"
    LDFLAGS="-mmacosx-version-min=10.7"
Traceback (most recent call last):
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1674, in <module>
    installer(args=sys.argv, log=sys.stdout)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 250, in __init__
    self.build_dependencies(packages=packages)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 774, in build_dependencies
    getattr(self, 'build_%s'%i)()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1563, in build_wxpython
    self.call("./configure %s" % " ".join(config_opts), log=pkg_log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 353, in call
    return call(args, log=log, verbose=self.verbose, **kwargs)
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/libtbx/auto_build/installer_utils.py", line 53, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to './configure --prefix="/Users/rjgildea/software/cctbx/base" --with-opengl --enable-unicode --without-libjbig --without-liblzma --with-libjpeg=builtin --enable-optimize --disable-debugreport --with-osx_cocoa --with-macosx-version-min=10.7 --with-mac --enable-monolithic --disable-mediactrl CPPFLAGS="-D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1 -mmacosx-version-min=10.7" LDFLAGS="-mmacosx-version-min=10.7"' failed with exit code 1
Process failed with return code 1
```
Running bootstrap with --wxpython4 appears to complete successfully.
`$ python bootstrap.py --builder=dials --nproc=8 --git-ssh --wxpython4
`

**Comment by rjgildea** [comment]
Resolved by d6f0f74 and e9d68f7.
