### ISSUE TITLE
bootstrap error building cairo

### ISSUE THREAD

**Issue by dsclassen** [cctbx/cctbx_project#337]
CentOS Linux release 7.6.1810 (Core) 
Python 2.7.5
wget https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py
python bootstrap.py 

```
Installing cairo...
  log file is /home/classen/cctbx/base_tmp/cairo_install_log
  getting package cairo-1.14.4.tar.gz...
    downloading from http://cci.lbl.gov/cctbx_dependencies : 43.4 MB
    [0%.........20%.........40%.........60%.........80%.........100%]
  installing cairo-1.14.4.tar.gz...
Traceback (most recent call last):
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1674, in <module>
    installer(args=sys.argv, log=sys.stdout)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 250, in __init__
    self.build_dependencies(packages=packages)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 774, in build_dependencies
    getattr(self, 'build_%s'%i)()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1411, in build_cairo
    self.build_compiled_package_simple(pkg_name=pkg, pkg_name_label=name)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 584, in build_compiled_package_simple
    self.configure_and_build(config_args=config_args, log=pkg_log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 572, in configure_and_build
    self.call("make -j %d %s" % (nproc, " ".join(list(make_args))), log=log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 353, in call
    return call(args, log=log, verbose=self.verbose, **kwargs)
  File "/home/classen/cctbx/modules/cctbx_project/libtbx/auto_build/installer_utils.py", line 53, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to 'make -j 1 ' failed with exit code 2
Process failed with return code 1```

**Comment by dsclassen** [comment]
UPDATE:

I decided to try using just the cctbx builder thusly:
```
python bootstrap.py --builder=cctbx --force-base-build
```
and this succeeded in building cairo, but then failed on wxPython.

```
Installing wxPython...
  log file is /home/classen/cctbx/base_tmp/wxPython_install_log
  getting package wxPython-src-3.0.2.0.tar.bz2...
    downloading from http://cci.lbl.gov/cctbx_dependencies : 55.6 MB
    [0%.........20%.........40%.........60%.........80%.........100%]
  installing wxPython-src-3.0.2.0.tar.bz2...
  building wxWidgets with options:
    --prefix="/home/classen/cctbx/base"
    --with-opengl
    --enable-unicode
    --without-libjbig
    --without-liblzma
    --with-libjpeg=builtin
    --enable-optimize
    --disable-debugreport
    --with-gtk
    --with-gtk-prefix="/home/classen/cctbx/base"
    --with-gtk-exec-prefix="/home/classen/cctbx/base/lib"
    --enable-graphics_ctx
    --disable-mediactrl
    --enable-display
    --without-libnotify
Traceback (most recent call last):
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1674, in <module>
    installer(args=sys.argv, log=sys.stdout)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 250, in __init__
    self.build_dependencies(packages=packages)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 774, in build_dependencies
    getattr(self, 'build_%s'%i)()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1563, in build_wxpython
    self.call("./configure %s" % " ".join(config_opts), log=pkg_log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 353, in call
    return call(args, log=log, verbose=self.verbose, **kwargs)
  File "/home/classen/cctbx/modules/cctbx_project/libtbx/auto_build/installer_utils.py", line 53, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to './configure --prefix="/home/classen/cctbx/base" --with-opengl --enable-unicode --without-libjbig --without-liblzma --with-libjpeg=builtin --enable-optimize --disable-debugreport --with-gtk --with-gtk-prefix="/home/classen/cctbx/base" --with-gtk-exec-prefix="/home/classen/cctbx/base/lib" --enable-graphics_ctx --disable-mediactrl --enable-display --without-libnotify' failed with exit code 1
Process failed with return code 1
```


Perhaps the order of dependencies being built is different between the main builder and the cctbx one?

I will continue to troubleshoot.

**Comment by dsclassen** [comment]
UPDATE #2:

running ```python bootstrap.py``` the third time completed.....huh?

In a clean virtualenv using the system python 2.7.5 the first bootstrap attempt fails:

```
python bootstrap.py
```
failed on cairo

```
python bootstrap.py --builder=cctbx --force-base-build
```
failed in wxPython.

```
python bootstrap.py
```
success
