### ISSUE TITLE
test scitbx.linalg.tests.tst_svd unstable

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#340]
Presumably randomised test, observed failing on Mac.

```
Error Message:
AssertionError

Stack Trace:
Traceback (most recent call last):
  File "/Users/dlshudson/jenkins_slave/workspace/dials_package_macos_tensix/build_dials/modules/cctbx_project/scitbx/linalg/tests/tst_svd.py", line 311, in 
    full_coverage=full_coverage)
  File "/Users/dlshudson/jenkins_slave/workspace/dials_package_macos_tensix/build_dials/modules/cctbx_project/scitbx/linalg/tests/tst_svd.py", line 296, in run
    run_for_class(show_progress, exercise_tntbx, full_coverage, scitbx.linalg.svd.real)
  File "/Users/dlshudson/jenkins_slave/workspace/dials_package_macos_tensix/build_dials/modules/cctbx_project/scitbx/linalg/tests/tst_svd.py", line 279, in run_for_class
    exercise_inverse()
  File "/Users/dlshudson/jenkins_slave/workspace/dials_package_macos_tensix/build_dials/modules/cctbx_project/scitbx/linalg/tests/tst_svd.py", line 273, in exercise_inverse
    assert approx_equal( uu[(aa,bb)], tmp,1e-3 )
AssertionError
```

**Comment by Anthchirp** [comment]
and on Linux
```
Traceback (most recent call last):
  File "/scratch/jenkins_agent/workspace/dials_test_linux/dials-dev20190702/modules/cctbx_project/scitbx/linalg/tests/tst_svd.py", line 312, in <module>
    full_coverage=full_coverage)
  File "/scratch/jenkins_agent/workspace/dials_test_linux/dials-dev20190702/modules/cctbx_project/scitbx/linalg/tests/tst_svd.py", line 297, in run
    run_for_class(show_progress, exercise_tntbx, full_coverage, scitbx.linalg.svd.real)
  File "/scratch/jenkins_agent/workspace/dials_test_linux/dials-dev20190702/modules/cctbx_project/scitbx/linalg/tests/tst_svd.py", line 280, in run_for_class
    exercise_inverse()
  File "/scratch/jenkins_agent/workspace/dials_test_linux/dials-dev20190702/modules/cctbx_project/scitbx/linalg/tests/tst_svd.py", line 274, in exercise_inverse
    assert approx_equal( uu[(aa,bb)], tmp,1e-3 )
AssertionError

Standard Output

Executing for: <class 'scitbx.linalg.svd.real'>
approx_equal eps: 0.001
approx_equal multiplier: 10000000000.0
0.996077435956 approx_equal ERROR
1.0 approx_equal ERROR
```
