### ISSUE TITLE
rstbx/indexing_api/tools broken on Python3

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#359]
to reproduce:
```
$ python -V
Python 3.6.7
$ python -c "import rstbx.indexing_api.tools"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "cctbx_project/rstbx/indexing_api/tools.py", line 40, in <module>
    spiral_order = generate_spiral_order()
  File "cctbx_project/rstbx/indexing_api/tools.py", line 36, in generate_spiral_order
    points.sort(radcmp)
TypeError: must use keyword argument for key function
```

**Comment by nksauter** [comment]
Please assign this one to me.
Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713
