### ISSUE TITLE
smtbx/ab_initio/tests/tst_charge_flipping.py broken on Python 3

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#362]
loads of tests still failing on python 3. This one is run by azure:
https://dev.azure.com/cctbx/cctbx_project/_build/results?buildId=184

command to run is apparently `libtbx.python smtbx/ab_initio/tests/tst_charge_flipping.py --fix_seed --on=E "hall: P 1" "hall: P 3" "hall: -P 2ybc"`
```
  Standard error:
    Traceback (most recent call last):
      File "/__w/1/modules/cctbx_project/smtbx/ab_initio/tests/tst_charge_flipping.py", line 241, in <module>
        run()
      File "/__w/1/modules/cctbx_project/smtbx/ab_initio/tests/tst_charge_flipping.py", line 238, in run
        exercise_charge_flipping()
      File "/__w/1/modules/cctbx_project/smtbx/ab_initio/tests/tst_charge_flipping.py", line 234, in exercise_charge_flipping
        symbols_to_stderr=False,
      File "/__w/1/modules/cctbx_project/cctbx/development/debug_utils.py", line 121, in parse_options_loop_space_groups
        show_cpu_times, **kwds)
      File "/__w/1/modules/cctbx_project/cctbx/development/debug_utils.py", line 84, in loop_space_groups
        call_back_result = call_back(flags, space_group_info, **kwds)
      File "/__w/1/modules/cctbx_project/smtbx/ab_initio/tests/tst_charge_flipping.py", line 221, in exercise
        amplitude_type=flags.on
      File "/__w/1/modules/cctbx_project/smtbx/ab_initio/tests/tst_charge_flipping.py", line 44, in randomly_exercise
        amplitude_type=amplitude_type,
      File "/__w/1/modules/cctbx_project/smtbx/ab_initio/tests/tst_charge_flipping.py", line 86, in exercise_one_structure
        charge_flipping.loop(solving, verbose="highly", out=s)
      File "/__w/1/modules/cctbx_project/smtbx/ab_initio/charge_flipping.py", line 558, in loop
        for flipping in solving:
      File "/__w/1/modules/cctbx_project/smtbx/ab_initio/charge_flipping.py", line 390, in __iter__
        try: state = next(self.state)
      File "/__w/1/modules/cctbx_project/smtbx/ab_initio/charge_flipping.py", line 470, in _guessing_delta_with_map_sigma
        sigma = self.flipping_iterator.rho_map.sigma()
    AttributeError: 'fft_map' object has no attribute 'sigma'
```

**Comment by rjgildea** [comment]
This is why this test is failing: `libtbx.object_oriented_patterns.injector` and `libtbx.object_oriented_patterns.memoize` were never converted to be Python 3 compatible, and their tests are simply skipped on Python 3:
https://github.com/cctbx/cctbx_project/blob/0385ba220080aebda3b9a2b0be51169de1db0182/libtbx/tst_object_oriented_patterns.py#L176-L180

Both classes are used in smtbx, e.g. here:
https://github.com/cctbx/cctbx_project/blob/de4faf1ba82457be021e0068cfbc8bf9318595e5/smtbx/ab_initio/charge_flipping.py#L83-L109

**Comment by phyy-nx** [comment]
Similar to #372, @bkpoon and I think @luc-j-bourhis needs to fix this. Assigning this issue to him (thanks Luc)
