### ISSUE TITLE
iotbx/mtz test broken

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#393]
(Presumably) following the fix for #321 the following thing happens:
```
Traceback (most recent call last):
  File "/scratch/jenkins_agent/workspace/cctbx_tests/build_dials/modules/cctbx_project/iotbx/regression/tst_merging_statistics.py", line 216, in <module>
    exercise(debug=("--debug" in sys.argv))
  File "/scratch/jenkins_agent/workspace/cctbx_tests/build_dials/modules/cctbx_project/iotbx/regression/tst_merging_statistics.py", line 166, in exercise
    else: raise Exception_expected
RuntimeError: Exception expected.
```

**Comment by Anthchirp** [comment]
`libtbx.python $(libtbx.find_in_repositories iotbx/regression/tst_merging_statistics.py)`, needs phenix_regression

**Comment by graeme-winter** [comment]
```ws168 pnx :) $ libtbx.python $(libtbx.find_in_repositories iotbx/regression/tst_merging_statistics.py)
OK```

following `libtbx.configure phenix_regression` - on RHEL6

**Comment by Anthchirp** [comment]
The relevant bit of the ~200 line function is captured by:
```
iotbx.merging_statistics /dls/tmp/wra62962/directories/phenix-regression/reflection_files/i_anomalous.mtz
```
which is supposed to crash with 
```
Sorry: The data in i_anomalous(+),SIGi_anomalous(+),i_anomalous(-),SIGi_anomalous(-) are already merged.  Only unmerged (but scaled) data may be used in this program.
```
and no longer does

**Comment by graeme-winter** [comment]
It's because input data _are_ anomalous and the anomalous flag is set to `False` so there is some redundancy but the results are nonsense:

```
                    ----------Merging statistics----------                    

Resolution: 100.45 - 2.43
Observations: 183
Unique reflections: 100
Redundancy: 1.8
Completeness: 0.77%
Mean intensity: 5959.4
Mean I/sigma(I): 18.1
R-merge: 0.058
R-meas:  0.081
R-pim:   0.058

Redundancies (non-anomalous):
  1 : 17
  2 : 83

  Statistics by resolution bin:
 d_max  d_min   #obs  #uniq   mult.  %comp       <I>  <I/sI>    r_mrg   r_meas    r_pim   cc1/2   cc_ano
100.53   5.25    172     92    1.87   7.03    6310.2    18.8    0.058    0.082    0.058   0.988   0.000
  5.25   4.16      7      5    1.40   0.48    3057.9    16.8    0.051    0.072    0.051   1.000   0.000
  4.16   3.64      0      0    0.00   0.00       0.0     0.0     None     None     None   0.000   0.000
  3.64   3.30      0      0    0.00   0.00       0.0     0.0     None     None     None   0.000   0.000
  3.30   3.07      0      0    0.00   0.00       0.0     0.0     None     None     None   0.000   0.000
  3.07   2.89      0      0    0.00   0.00       0.0     0.0     None     None     None   0.000   0.000
  2.89   2.74      0      0    0.00   0.00       0.0     0.0     None     None     None   0.000   0.000
  2.74   2.62      0      0    0.00   0.00       0.0     0.0     None     None     None   0.000   0.000
  2.62   2.52      0      0    0.00   0.00       0.0     0.0     None     None     None   0.000   0.000
  2.52   2.43      4      3    1.33   0.24      39.7     0.7    0.227    0.320    0.227   0.000   0.000
100.45   2.43    183    100    1.83   0.77    5959.4    18.1    0.058    0.081    0.058   0.987   0.000

References:
  Diederichs K & Karplus PA (1997) Nature Structural Biology 4:269-275
    (with erratum in: Nat Struct Biol 1997 Jul;4(7):592)
  Weiss MS (2001) J Appl Cryst 34:130-135.
  Karplus PA & Diederichs K (2012) Science 336:1030-3.


```

**Comment by Anthchirp** [comment]
issue is that `params.anomalous==False` by default,
https://github.com/cctbx/cctbx_project/blob/ea27b75fa815338c1b2a1cfddc0a00d9ade04ec5/iotbx/merging_statistics.py#L51-L53
which is passed in
https://github.com/cctbx/cctbx_project/blob/ea27b75fa815338c1b2a1cfddc0a00d9ade04ec5/iotbx/command_line/merging_statistics.py#L90-L96
which then triggers the new code, whereas passing `None` would cause it to stick to the old code path and would work
