### ISSUE TITLE
boost.python.injector warning when importing boost.python

### ISSUE THREAD

**Issue by rjgildea** [cctbx/cctbx_project#397]
Simply importing the `boost.python` module causes a warning to be emitted:
```
$ dials.python -W error -c "import boost.python"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/boost/python.py", line 188, in <module>
    class injector(object):
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/boost/python.py", line 206, in __init__
    stacklevel=2
DeprecationWarning: boost.python.injector is deprecated and does not work on Python 3. Please see https://github.com/cctbx/cctbx_project/pull/386 for more information.
```
This causes warnings to be raised when running pytest e.g. on dials:
```
============================================================================================= warnings summary =============================================================================================
/Users/rjgildea/software/cctbx/modules/cctbx_project/boost/python.py:188
  /Users/rjgildea/software/cctbx/modules/cctbx_project/boost/python.py:188: DeprecationWarning:
  
  boost.python.injector is deprecated and does not work on Python 3. Please see https://github.com/cctbx/cctbx_project/pull/386 for more information.
...
```

**Comment by Anthchirp** [comment]
this was fixed in 945e548c9f07c617465febfba1d63f26b9e569e4
