### ISSUE TITLE
excessive memory usage opening large files

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#42]
```
Hi folks,

I have a multi-image file, a copy of which is at /dls/tmp/david/Lys2_grid3_diffraction_lamella2_noSA_1.ser. This is a 7.4G file containing 117 diffraction images. Starting dials.image_viewer with this file is okay - the process uses 711M virtual memory on my computer. When I click 'Next' this goes up to 793M. Click 'Next' again and it settles at 1049M. As I keep clicking 'Next' this total increases. By image 20 it is at 5017M.

If I try to jump from image 20 to 117 the image viewer greys out, the virtual memory usage leaps to 10.9G and eventually there is a traceback in the terminal:

Traceback (most recent call last):
  File "/home/david/sw/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 202, in OnChooseImage
    super(SpotFrame, self).OnChooseImage(event)
  File "/home/david/sw/cctbx/modules/cctbx_project/rstbx/viewer/frame.py", line 328, in OnChooseImage
    self.image_chooser.GetSelection()))
  File "/home/david/sw/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 470, in load_image
    show_untrusted=show_untrusted)
  File "/home/david/sw/cctbx/modules/cctbx_project/rstbx/slip_viewer/frame.py", line 345, in load_image
    get_raw_data=get_raw_data)
  File "/home/david/sw/cctbx/modules/cctbx_project/rstbx/slip_viewer/tile_generation.py", line 250, in set_image
    self.raw_image.set_raw_data(get_raw_data(self.raw_image))
  File "/home/david/sw/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 737, in get_raw_data
    raw_data = image.get_raw_data()
  File "/home/david/sw/cctbx/modules/cctbx_project/rstbx/slip_viewer/frame.py", line 37, in get_raw_data
    self._raw_data = self.image_set[self.index]
  File "/home/david/sw/cctbx/modules/cctbx_project/dxtbx/imageset.py", line 1155, in __getitem__
    return self.get_corrected_data(item)
  File "/home/david/sw/cctbx/modules/cctbx_project/dxtbx/imageset.py", line 570, in get_corrected_data
    data = self.get_raw_data(index)
  File "/home/david/sw/cctbx/modules/cctbx_project/dxtbx/imageset.py", line 559, in get_raw_data
    image = self.reader().read(self._indices[index])
  File "/home/david/sw/cctbx/modules/cctbx_project/dxtbx/imageset.py", line 181, in read
    return self.get_format().get_raw_data(index)
  File "/home/david/sw/cctbx/modules/cctbx_project/dxtbx/format/FormatSEReBIC.py", line 73, in get_raw_data
    raw_data = super(FormatSEReBIC, self).get_raw_data(index)
  File "/home/david/sw/cctbx/modules/cctbx_project/dxtbx/format/FormatSER.py", line 145, in get_raw_data
    d['CalibrationOffsetX'] = struct.unpack('<d', f.read(8))[0]
  File "/home/david/sw/cctbx/modules/cctbx_project/dxtbx/filecache.py", line 314, in read
    data, self._seek = self._cache_object.pass_read(start=self._seek, maxbytes=size)
  File "/home/david/sw/cctbx/modules/cctbx_project/dxtbx/filecache.py", line 211, in pass_read
    self._cache_up_to(start + maxbytes)
  File "/home/david/sw/cctbx/modules/cctbx_project/dxtbx/filecache.py", line 116, in _cache_up_to
    self._cache_object.write(data)
OverflowError: length too large


Why is this happening like this? Is it something to do with the dxtbx file cache?

Cheers
David
```

**Comment by dagewa** [comment]
I repeated the test. It is better, but after clicking through to image 20 VIRT still crawls up, to 3033M. Jumping from there to the end did not fail though, and ended up at 3161M. I then randomly jump around a few images. Each time I get an increment in the memory footprint of 128M. Therefore reopening...

**Comment by Anthchirp** [comment]
not filecache related

**Comment by dagewa** [comment]
With this test case, the first press of 'Next' gains 18M of memory footprint, subsequent presses all gain 128M. RAM usage monitored manually using htop. We don't know where the remaining memory leak lies yet.

**Comment by Anthchirp** [comment]
Other memory leak not limited to large files, maybe dials-issue, not cctbx. Moved to new ticket in dials land anyway: dials/dials#378.
