### ISSUE TITLE
cctbx.xray.structure.from_cif() cannot parse some files from COD

### ISSUE THREAD

**Issue by wojdyr** [cctbx/cctbx_project#461]
I ran xray.structure.from_cif() on a subset of COD.
Reading wavelength in some files (for example 2021610.cif 2021613.cif 2020698.cif) raises exception:

```
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cctbx import xray
>>> xray.structure.from_cif(file_path='cif/2/02/16/2021610.cif')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wojdyr/miniconda3/lib/python3.7/site-packages/cctbx/xray/structure.py", line 2328, in from_cif
    data_structure_builder=builders.crystal_structure_builder)
  File "/home/wojdyr/miniconda3/lib/python3.7/site-packages/iotbx/cif/__init__.py", line 387, in __init__
    self.xray_structures.setdefault(key, builder(block).structure)
  File "/home/wojdyr/miniconda3/lib/python3.7/site-packages/iotbx/cif/builders.py", line 307, in __init__
    wavelength = float(wvl_str) if (wvl_str and wvl_str!='?') else None
TypeError: float() argument must be a string or a number, not 'std_string'
```

or

```
    wavelength = float(wvl_str) if (wvl_str and wvl_str!='?') else None
ValueError: could not convert string to float: '0.399927(2)'
```

I'm using cctbx installed with "conda install -c conda-forge -c cctbx-dev cctbx".

**Comment by olegsobolev** [comment]
Thanks for pointing it out.
First issue fix: https://github.com/cctbx/cctbx_project/commit/4b79c3f0bc9971783e6f9324528daa31cb7ab66d
Second issue fix: https://github.com/cctbx/cctbx_project/commit/784fdb74fc3731be38057052bc002a3a5c9cce11

**Comment by bkpoon** [comment]
I can build updated `conda` test packages this weekend with the latest changes.

**Comment by wojdyr** [comment]
Thanks for quick response!
