### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by sarisabban** [cctbx/cctbx_project#480]
I am trying to install CCTBX using the bootstrap.py script on Ubuntu 20.04 using python 3.8

But I am getting this error:

`installing libffi-3.2.1.tar.gz...
Installing glib...
  log file is /home/acresearch/Desktop/CCTBX/base_tmp/glib_install_log
  getting package glib-2.46.2.tar.gz...
    downloading from http://cci.lbl.gov/cctbx_dependencies/glib-2.46.2.tar.gz : 14.1 MB
    [0%.........20%.........40%.........60%.........80%.........100%]
  installing glib-2.46.2.tar.gz...
Traceback (most recent call last):
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1682, in <module>
    installer(args=sys.argv, log=sys.stdout)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 256, in __init__
    self.build_dependencies(packages=packages)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 782, in build_dependencies
    getattr(self, 'build_%s'%i)()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1315, in build_glib
    log=pkg_log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 580, in configure_and_build
    self.call("make -j %d %s" % (nproc, " ".join(list(make_args))), log=log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 359, in call
    return call(args, log=log, verbose=self.verbose, **kwargs)
  File "/home/acresearch/Desktop/CCTBX/modules/cctbx_project/libtbx/auto_build/installer_utils.py", line 55, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to 'make -j 1 ' failed with exit code 2
Process failed with return code 1`

I am not sure how to fix this issue, can anyone help me?

**Comment by bkpoon** [comment]
So to support newer operating systems more easily, we're using [conda](https://docs.conda.io/en/latest/) for dependencies. You can modify your `bootstrap.py` command with the `--use-conda` flag and that will get you up and running. Our default is still Python 2.7, but you can try Python 3 (3.6 - 3.8) by adding the `--python` flag. For example, if you wanted to build a Python 3.8 version with conda, your `bootstrap.py` command would look like,
```
python bootstrap.py --use-conda --python 38
```
That will install `conda` for you as well (in a `mc3` directory) if you do not have an existing installation.

**Comment by bkpoon** [comment]
Additionally, we have test conda packages for cctbx in the `cctbx-dev` channel. If you already have conda installed, you can get the Python 3.8 package with,
```
conda create -n <env name> -c cctbx-dev -c conda-forge cctbx python=3.8
```
That creates a new conda environment with Python 3.8 and cctbx. The package was last updated in April. There is a May package, but it's a work in progress and may not work correctly.

**Comment by sarisabban** [comment]
That works well...

Thank you.
