### ISSUE TITLE
test cctbx/regression/tst_grm_modifications.py broken

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#518]
And has been since [at least March 2019](https://github.com/dials/cctbx/commit/d0701c3608db4313ebbcc37597d2a3324aaec60c).

As the test is skipped unless CCP4 is present we only notice its failure during our release process, at which point we manually [disable](https://github.com/dials/cctbx/commit/a0357cb4d86d2455393d8e206a96e6c01bae0f63) [the](https://github.com/dials/cctbx/commit/3a111203f841b0f4fb2f21943902840c5dbd427b) [test](https://github.com/dials/cctbx/commit/1d3631940c6d544903d3e074af9c86364c67b618) [every](https://github.com/dials/cctbx/commit/87aa99259d9a5fd90e77d6c4a339a5dc6a58c7f0) [time](https://github.com/dials/cctbx/commit/8050c4b3112736f83897fff733117e3cc22d6f1e).

Thought you might want to know.

**Comment by olegsobolev** [comment]
Works for me everywhere. Even on all Azure pipelines (e.g. [here](https://dev.azure.com/cctbx/cctbx_project/_build/results?buildId=8288&view=logs&jobId=f73154b7-efd9-54b4-9cbb-e74e12ba7819&j=640266b1-0bf4-514a-e546-04d76177084c&t=fe2c4bf7-e9ad-599d-c161-afbcd274af45))

Any helpful debugging info?

**Comment by Anthchirp** [comment]
This is the test output:
```
Sorry: Fatal problems interpreting model file:
 Number of atoms with unknown nonbonded energy type symbols: 2
 Please edit the model file to resolve the problems and/or supply a
 CIF file with matching restraint definitions, along with
 apply_cif_modification and apply_cif_link parameter definitions
 if necessary.
```

**Comment by nwmoriarty** [comment]
Looks like the CCP4 restraints library has different ideas about the atom
names compared to Phenix library. To debug, we need more output from the
test. Setting the env. var. LIBTBX_DISABLE_TRACEBACKLIMIT to 1 will do the
trick. Can you provide the augmented error message?

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by Anthchirp** [comment]
This is with DIALS 3.0.4 and CCP4 7.1.0:
```
$ LIBTBX_DISABLE_TRACEBACKLIMIT=1 dials.python /dls_sw/apps/dials/dials-v3-0-4/modules/cctbx_project/cctbx/regression/tst_grm_modifications.py 
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-0-4/modules/cctbx_project/cctbx/regression/tst_grm_modifications.py", line 684, in <module>
    exercise()
  File "/dls_sw/apps/dials/dials-v3-0-4/modules/cctbx_project/cctbx/regression/tst_grm_modifications.py", line 680, in exercise
    exercise_bond_over_symmetry(mon_lib_srv, ener_lib)
  File "/dls_sw/apps/dials/dials-v3-0-4/modules/cctbx_project/cctbx/regression/tst_grm_modifications.py", line 526, in exercise_bond_over_symmetry
    grm = model.get_restraints_manager().geometry
  File "/dls_sw/apps/dials/dials-v3-0-4/modules/cctbx_project/mmtbx/model/model.py", line 677, in get_restraints_manager
    self.setup_restraints_manager()
  File "/dls_sw/apps/dials/dials-v3-0-4/modules/cctbx_project/mmtbx/model/model.py", line 1198, in setup_restraints_manager
    self._process_input_model()
  File "/dls_sw/apps/dials/dials-v3-0-4/modules/cctbx_project/mmtbx/model/model.py", line 1124, in _process_input_model
    allow_missing_symmetry=True)
  File "/dls_sw/apps/dials/dials-v3-0-4/modules/cctbx_project/mmtbx/utils/__init__.py", line 1007, in process_pdb_files
    allow_missing_symmetry   = allow_missing_symmetry)
  File "/dls_sw/apps/dials/dials-v3-0-4/modules/cctbx_project/mmtbx/utils/__init__.py", line 1092, in _process_pdb_file
    raise Sorry(msg)
Sorry: Fatal problems interpreting model file:
  Number of atoms with unknown nonbonded energy type symbols: 2
    Please edit the model file to resolve the problems and/or supply a
    CIF file with matching restraint definitions, along with
    apply_cif_modification and apply_cif_link parameter definitions
    if necessary.
```

**Comment by ndevenish** [comment]
Still finding this, bypassing for release again https://github.com/dials/cctbx/commit/f217ceb32920ff4547e1cd7b26cb94e9ae3328d0
