### ISSUE TITLE
bootstrap broken on mac

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#55]
1c6d48f4bd12d4cf2786f35f98e7b6f9892121a7 broke mac builds

build log snippet:

```
(...)
: 
: Python build finished, but the necessary bits to build these modules were not found:
: _bsddb             dl                 gdbm
: imageop            linuxaudiodev      ossaudiodev
: readline           spwd               sunaudiodev
: To find the necessary bits, look in setup.py in detect_modules() for the module's name.
: 
: running build_scripts
: running install_lib
(...)
: running install_scripts
(..)
: running install_egg_info
(..)
: build
: Building './Python Launcher.app'
: Copying files
: Done.
: test -d "/Applications/Python 2.7" || mkdir -p "/Applications/Python 2.7"
: test -d "/Applications/Python 2.7/Python Launcher.app" && rm -r "/Applications/Python 2.7/Python Launcher.app"
: make[2]: [install] Error 1 (ignored)
: /bin/cp -r "Python Launcher.app" "/Applications/Python 2.7"
: cp: /Applications/Python 2.7/Python Launcher.app: Permission denied
: cp: Python Launcher.app: unable to copy extended attributes to /Applications/Python 2.7/Python Launcher.app: Permission denied
: cp: /Applications/Python 2.7/Python Launcher.app/Contents: No such file or directory
: cp: Python Launcher.app/Contents: unable to copy extended attributes to /Applications/Python 2.7/Python Launcher.app/Contents: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Info.plist: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/MacOS: No such file or directory
: cp: Python Launcher.app/Contents/MacOS: unable to copy extended attributes to /Applications/Python 2.7/Python Launcher.app/Contents/MacOS: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/MacOS/Python Launcher: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/PkgInfo: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources: No such file or directory
: cp: Python Launcher.app/Contents/Resources: unable to copy extended attributes to /Applications/Python 2.7/Python Launcher.app/Contents/Resources: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj: No such file or directory
: cp: Python Launcher.app/Contents/Resources/English.lproj: unable to copy extended attributes to /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/Credits.rtf: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/MainMenu.nib: No such file or directory
: cp: Python Launcher.app/Contents/Resources/English.lproj/MainMenu.nib: unable to copy extended attributes to /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/MainMenu.nib: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/MainMenu.nib/classes.nib: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/MainMenu.nib/info.nib: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/MainMenu.nib/objects.nib: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/MyDocument.nib: No such file or directory
: cp: Python Launcher.app/Contents/Resources/English.lproj/MyDocument.nib: unable to copy extended attributes to /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/MyDocument.nib: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/MyDocument.nib/classes.nib: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/MyDocument.nib/info.nib: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/MyDocument.nib/objects.nib: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/PreferenceWindow.nib: No such file or directory
: cp: Python Launcher.app/Contents/Resources/English.lproj/PreferenceWindow.nib: unable to copy extended attributes to /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/PreferenceWindow.nib: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/PreferenceWindow.nib/classes.nib: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/PreferenceWindow.nib/info.nib: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/English.lproj/PreferenceWindow.nib/objects.nib: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/factorySettings.plist: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/PythonCompiled.icns: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/PythonLauncher.icns: No such file or directory
: cp: /Applications/Python 2.7/Python Launcher.app/Contents/Resources/PythonSource.icns: No such file or directory
: make[2]: *** [install] Error 1
: make[1]: *** [install_PythonLauncher] Error 2
: make: *** [frameworkinstallapps] Error 2
Traceback (most recent call last):
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1480, in <module>
    installer(args=sys.argv, log=sys.stdout)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 217, in __init__
    self.build_dependencies(packages=packages)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 683, in build_dependencies
    getattr(self, 'build_%s'%i)()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 748, in build_python
    self.call('make install', log=log, cwd=python_dir)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 307, in call
    return call(args, log=log, verbose=self.verbose, **kwargs)
  File "/Users/dlshudson/jenkins_slave/workspace/dials_bootstrap_platforms/label/dials-mac-mini/build_dials/modules/cctbx_project/libtbx/auto_build/installer_utils.py", line 81, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to 'make install' failed with exit code 2
Performing actions: base
```

**Comment by Anthchirp** [comment]
Problem is that ```make install``` implies ```make frameworkinstallapps``` which it didn't before and we can't do.

**Comment by ndevenish** [comment]
It also looks like you can also `make install DESTDIR=<somewhere>` to get a custom location for the `frameworkinstallapps` target. At least, it works on my machine. But I'm not sure it's any less fragile than explicit targets.

From reading the Python Makefile it also looks like it'd remove the requirement for separate call to ensurepip.

**Comment by bkpoon** [comment]
When running `make install DESTDIR=<somewhere>`, what does your `base` directory look like? Do you have IDLE and Python Launcher somewhere?

**Comment by bkpoon** [comment]
Let's see if [https://github.com/cctbx/cctbx_project/commit/e97fbce147079149aa4fcc6a54a392401e35e933](https://github.com/cctbx/cctbx_project/commit/e97fbce147079149aa4fcc6a54a392401e35e933) fixes the issue. There were some extra apps that used /Applications as the default location. I think explicitly removing these few items (`install_BuildApplet`, `install_PythonLauncher`, `install_IDLE`) is better than manually calling all the other individual rules in the Makefile.

**Comment by ndevenish** [comment]
> When running make install DESTDIR=<somewhere>, what does your base directory look like? Do you have IDLE and Python Launcher somewhere?

I meant that, by inspection of the python Makefiles and quick tests, `DESTDIR=$(pwd)/otherstuff` is passed straight through to the mac-specific makefiles so all the `Python Launcher`, `IDLE`, etc are put in there instead, because `PYTHONAPPDIR` is only ever used in the context of `$(DESTDIR)$(PYTHONAPPSDIR)`. This appears to be undocumented, but the behaviour appears to persist in the latest  code.

Also, the Mac-specific `Mac/README` does seem to [imply](https://github.com/python/cpython/blob/d81bea6520892e0428aec61c73e0631a69db11bb/Mac/README#L249-L251) individual targets is the recommended approach: "_If you want to install some part, but not all, read the main Makefile._"

**Comment by bkpoon** [comment]
Are the extra apps still being installed with e97fbce147079149aa4fcc6a54a392401e35e933? That commit changes the Makefile in the Mac directory so that the extra apps (`install_BuildApplet`, `install_PythonLauncher`, and `install_IDLE`) are not built at all and removes the `/Applications` path. We're not seeing any issues on macOS 10.9 through 10.12. Our test machines might not cover all cases, however, since we do not have a `/Applications/Python 2.7` directory, so the earlier code (1c6d48f4bd12d4cf2786f35f98e7b6f9892121a7) happily installed the extra apps with no error.

**Comment by Anthchirp** [comment]
Don't have a mac so won't look into it further but Jenkins seems happy now.
