### ISSUE TITLE
XFEL GUI is broken on wxpython 4.1

### ISSUE THREAD

**Issue by dwpaley** [cctbx/cctbx_project#568]
Hi all,
The current wxpython release doesn't like something in `cctbx.xfel` startup. This reproduces the bug on CentOS 7:

```
$ wget https://raw.githubusercontent.com/cctbx/cctbx_project/master/xfel/util/lcls_xfelgui_installer.sh
$ chmod +x lcls_xfelgui_installer.sh
$ mkdir dials
$  ./lcls_xfelgui_installer.sh $PWD/dials 64
$ source dials/setup.sh
$ cctbx.xfel

/dev/shm/dwpaley/test_issue/dials/dialsBuild/modules/dxtbx/model/__init__.py:11: FutureWarning: importing from boost.python is deprecated; this module will be removed shortly. import from boost_adaptbx.boost.python instead. Please see https://github.com/cctbx/cctbx_project/issues/458 for more information.
  import boost.python
Traceback (most recent call last):
  File "/dev/shm/dwpaley/test_issue/dials/dialsBuild/build/../modules/cctbx_project/xfel/ui/command_line/xfel_gui_launch.py", line 26, in OnInit
    self.frame = MainWindow(None, -1, title='CCTBX.XFEL')
  File "/dev/shm/dwpaley/test_issue/dials/dialsBuild/modules/cctbx_project/xfel/ui/components/xfel_gui_init.py", line 1077, in __init__
    self.run_window = RunWindow(self)
  File "/dev/shm/dwpaley/test_issue/dials/dialsBuild/modules/cctbx_project/xfel/ui/components/xfel_gui_init.py", line 1351, in __init__
    self.runs_tab = RunTab(self.main_nbook, main=self.parent)
  File "/dev/shm/dwpaley/test_issue/dials/dialsBuild/modules/cctbx_project/xfel/ui/components/xfel_gui_init.py", line 1441, in __init__
    border=10)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at /home/conda/feedstock_root/build_artifacts/wxpython_1603889841103/work/ext/wxWidgets/src/common/sizer.cpp(2098) in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
OnInit returned false, exiting...
```

This is fixed by pinning wxpython to 4.0.* in the conda yml file, but I imagine we'd rather not do that permanently.

Dan

**Comment by dwpaley** [comment]
Fixed by 79108f4b2
