### ISSUE TITLE
Remaining side effects for Eiger data sets following dxtbx refactor

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/cctbx_project#61]
e.g. 

```
Graemes-MacBook-Pro-5:index graeme$ dials.generate_mask  'input.datablock="SWEEP1_datablock.json"' 'output.mask="1_mask.pickle"' 'output.datablock="1_SWEEP1_datablock.json"' '1_mask.phil'
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/generate_mask.py", line 117, in <module>
    halraiser(e)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/generate_mask.py", line 115, in <module>
    script.run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/generate_mask.py", line 74, in run
    params, options = self.parser.parse_args(show_diff_phil=True)
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 783, in parse_args
    quick_parse=quick_parse)
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 454, in parse_args
    track_unused_definitions=True)
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/phil/__init__.py", line 1857, in fetch
    skip_incompatible_objects=skip_incompatible_objects)
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/phil/__init__.py", line 1881, in fetch
    source=candidate).as_str()
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/phil/__init__.py", line 1137, in extract_format
    return self.format(python_object=source.extract())
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/phil/__init__.py", line 1122, in extract
    return self._type_from_words()(self.words, master=self)
  File "/Users/graeme/svn/cctbx/modules/dials/util/phil.py", line 51, in from_words
    return self.from_string(libtbx.phil.str_from_words(words=words))
  File "/Users/graeme/svn/cctbx/modules/dials/util/phil.py", line 47, in from_string
    check_format=self._check_format))
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 920, in from_json_file
    return DataBlockFactory.from_json(infile.read(), check_format)
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 910, in from_json
    check_format)
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 898, in from_dict
    importer = DataBlockDictImporter(obj, check_format)
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 650, in __init__
    self.datablocks = self._load_datablocks(obj, check_format)
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 663, in _load_datablocks
    return [self._load_datablocks(dd, check_format) for dd in obj]
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 737, in _load_datablocks
    format_kwargs=format_kwargs)
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/dxtbx/imageset.py", line 1149, in make_sweep
    filenames = [template_format % (i+1) for i in range(*array_range)]
TypeError: Please report this error to dials-support@lists.sourceforge.net: unsupported operand type(s) for %: 'NoneType' and 'int'
```

Working now

**Comment by graeme-winter** [comment]
To reproduce:

```
dials.import ../trypsin_6_topup_2_1_master.h5 
DIALS 1.dev.1613-g74421ba9
The following parameters have been modified:

input {
  datablock = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatHDFEigerNearlyNexus.FormatEigerNearlyNexus'>
  num images: 12000
  num sweeps: 1
  num stills: 0
--------------------------------------------------------------------------------
Writing datablocks to datablock.json
```

```
dials.python tst.py
```

where tst.py is 

```
from dxtbx.datablock import DataBlockFactory
DataBlockFactory.from_json_file('datablock.json')
```

**Comment by graeme-winter** [comment]
Changes related to the fix:

dials/dials 1825af29e2a2962a3777fd1eba09014fa9b9a622
cctbx/cctbx_project 1f875774d60a576141843461f8422a2474cec452
cctbx/cctbx_project 0232e20392d220a88fe7cef6ba7ed8509333fa5e
cctbx/cctbx_project 1278704feadb45cc451b534363540758fc968d37
cctbx/cctbx_project d65eec1ef8b7582652bc96133e6cd307413126f5
