### ISSUE TITLE
xfel_regression test failure with psana=4.0.37

### ISSUE THREAD

**Issue by dwpaley** [cctbx/cctbx_project#744]
After building according to "General build" here: https://github.com/cctbx/cctbx_project/tree/master/xfel/conda_envs and configuring the xfel_regression tests, we get this failure:

```
$ libtbx.python ../modules/xfel_regression/test/command_line/tst_cxi_formatXTC.py
 Test for FormatXTCCspad in dxtbx. Compares the image object interpreted by FormatXTCCspad with the CBF output from xtc_process
Assertion results will be found at ./tmpswzh09q0_tst_cxi_formatXTC_39test_cxi0
Traceback (most recent call last):
  File "../modules/xfel_regression/test/command_line/tst_cxi_formatXTC.py", line 104, in <module>
    tester.run_all()
  File "../modules/xfel_regression/test/command_line/tst_cxi_formatXTC.py", line 96, in run_all
    self.test_cxid1916()
  File "../modules/xfel_regression/test/command_line/tst_cxi_formatXTC.py", line 50, in test_cxid1916
    result = easy_run.fully_buffered(command=command, stdout_splitlines=True).raise_if_errors()
  File "/dev/shm/dwpaley/20220311/modules/cctbx_project/libtbx/easy_run.py", line 46, in raise_if_errors
    raise Error(msg)
RuntimeError: child process stderr output:
  command: 'cctbx.xfel.xtc_process input.experiment=cxid9114 input.run_num=108 input.address=CxiDs2.0:Cspad.0                         dispatch.find_spots=False dispatch.dump_all=True format.cbf.detz_offset=100.1204                         dispatch.datasource=exp=cxid9114:run=108:xtc'
  Traceback (most recent call last):
    File "/dev/shm/dwpaley/20220311/build/../modules/cctbx_project/xfel/command_line/xtc_process.py", line 1404, in <module>
      script.run()
    File "/dev/shm/dwpaley/20220311/build/../modules/cctbx_project/xfel/command_line/xtc_process.py", line 797, in run
      psana_mask = self.psana_det.mask(run.run(),calib=True,status=True,edges=True,central=True,unbond=True,unbondnbrs=True)
    File "/dev/shm/dwpaley/20220311/conda_base/lib/python3.7/site-packages/Detector/AreaDetector.py", line 1174, in mask
      if status: mask_nda = gu.merge_masks(mask_nda, self.status_as_mask(par, **kwargs))
    File "/dev/shm/dwpaley/20220311/conda_base/lib/python3.7/site-packages/Detector/AreaDetector.py", line 737, in status_as_mask
      smask = np.asarray(np.select((stat & mstcode,), (0,), default=1), dtype=np.uint8)
    File "<__array_function__ internals>", line 6, in select
    File "/dev/shm/dwpaley/20220311/conda_base/lib/python3.7/site-packages/numpy/lib/function_base.py", line 701, in select
      'invalid entry {} in condlist: should be boolean ndarray'.format(i))
  TypeError: Please report this error to dials-support@lists.sourceforge.net: invalid entry 0 in condlist: should be boolean ndarray
usr+sys time: 1.93 seconds
wall clock time: 7.97 seconds
```

Can fix by downgrading psana to 4.0.36:
```
$ conda install psana=4.0.36 -c lcls-i -c conda-forge -c cctbx -c defaults -y
$ libtbx.python ../modules/xfel_regression/test/command_line/tst_cxi_formatXTC.py
 Test for FormatXTCCspad in dxtbx. Compares the image object interpreted by FormatXTCCspad with the CBF output from xtc_process
Assertion results will be found at ./tmpwlwzeyza_tst_cxi_formatXTC_39test_cxi0
OK
usr+sys time: 12.07 seconds
wall clock time: 28.64 seconds
```

**Comment by dwpaley** [comment]
This was discussed offline with Chris O'Grady and Mikhail Dubrovin. They implemented a fix, psana appears to work again and the version was unpinned in #754.

**Comment by phyy-nx** [comment]
🎉
