### ISSUE TITLE
test scitbx/lbfgs/tst_lbfgs_fem.py failing on mac

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#84]
our mac build server is back!

unfortunately there is one test failing:

```
/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/build/scitbx/lbfgs/sdrive_fem
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" fortran 100 5 1 0
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" fortran 2 6 -1 0
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" raw_reference 2 6 -1 0
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" raw 2 6 -1 0
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" fortran 14 3 -1 1
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" raw_reference 14 3 -1 1
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" raw 14 3 -1 1
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" fortran 4 4 -1 2
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" raw_reference 4 4 -1 2
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" raw 4 4 -1 2
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" fortran 2 3 -1 3
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" raw_reference 2 3 -1 3
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" raw 2 3 -1 3
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" fortran 14 5 0 0
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" raw_reference 14 5 0 0
scitbx.python "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py" raw 14 5 0 0
--- 
+++ 
@@ -7,7 +7,7 @@
    I   NFN    FUNC        GNORM       STEPLENGTH
 
    1    2       1.5E+02     4.3E+02     1.6E-03
-  35   44       0.0E-16     3.6E-07     1.0E+00
+  35   44       0.0E-17     7.3E-08     1.0E+00
 
  THE MINIMIZATION TERMINATED WITHOUT DETECTING ERRORS.
  IFLAG = 0

Traceback (most recent call last):
  File "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py", line 165, in <module>
    run(sys.argv[1:])
  File "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py", line 160, in run
    compare_implementations()
  File "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py", line 136, in compare_implementations
    this_script=this_script, n=n, m=m, iprint=[iprint1, iprint2])
  File "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/scitbx/lbfgs/tst_lbfgs_fem.py", line 123, in run_and_compare_implementations
    assert abs(float(gnorma) - float(gnormb)) <= 1e-7
AssertionError
```

Given that 
* lbfgs code hasn't changed in a while
* this is a new machine (10.12), and 
* the last commit in that area was due to a newer version of XCode being deployed (https://github.com/cctbx/cctbx_project/commit/eff49a40fe1ff24379959386902a5c9df23eb204)

I strongly suspect that this failing test is just some 'it just works!' Mac nonsense.

**Comment by Anthchirp** [comment]
waiting for tests on build mac regarding xcode before deploying this

**Comment by Anthchirp** [comment]
xcode issue was unrelated
