### ISSUE TITLE
xtriage fail on loggraph

### ISSUE THREAD

**Issue by frankvm04** [cctbx/cctbx_project#970]
Calling xtriage fails. Tested using SBGrid implementation on both Linux and Mac. 1.20-4459, 1.20.1-4487, and 1.19.2-4158 function, but 1.21rc1-5107, 1.21rc1-5127, and 1.21-5207 all fail.

`phenix.xtriage NE10_13_CGH_RJS_1_free.mtz  scaling.input.xray_data.obs_labels="I(+),SIGI(+),I(-),SIGI(-)" scaling.input.parameters.reporting.loggraphs=True`

Yields

```bash
Traceback (most recent call last):
  File "/opt/sbgrid/i386-mac/phenix/1.21rc1-5127/phenix-1.21rc1-5127/build/../modules/cctbx_project/mmtbx/command_line/xtriage.py", line 9, in <module>
    xtriage.run(args=sys.argv[1:])
  File "/opt/sbgrid/i386-mac/phenix/1.21rc1-5127/phenix-1.21rc1-5127/modules/cctbx_project/mmtbx/scaling/xtriage.py", line 1397, in run
    xtriage_results.show(out=graph_out)
  File "/opt/sbgrid/i386-mac/phenix/1.21rc1-5127/phenix-1.21rc1-5127/modules/cctbx_project/mmtbx/scaling/__init__.py", line 236, in show
    self._show_impl(out=out)
  File "/opt/sbgrid/i386-mac/phenix/1.21rc1-5127/phenix-1.21rc1-5127/modules/cctbx_project/mmtbx/scaling/xtriage.py", line 852, in _show_impl
    self.data_strength_and_completeness.show(out)
  File "/opt/sbgrid/i386-mac/phenix/1.21rc1-5127/phenix-1.21rc1-5127/modules/cctbx_project/mmtbx/scaling/__init__.py", line 236, in show
    self._show_impl(out=out)
  File "/opt/sbgrid/i386-mac/phenix/1.21rc1-5127/phenix-1.21rc1-5127/modules/cctbx_project/mmtbx/scaling/data_statistics.py", line 827, in _show_impl
    self.data_strength.show(out)
  File "/opt/sbgrid/i386-mac/phenix/1.21rc1-5127/phenix-1.21rc1-5127/modules/cctbx_project/mmtbx/scaling/__init__.py", line 236, in show
    self._show_impl(out=out)
  File "/opt/sbgrid/i386-mac/phenix/1.21rc1-5127/phenix-1.21rc1-5127/modules/cctbx_project/mmtbx/scaling/data_statistics.py", line 117, in _show_impl
    out.show_plot(self.table)
  File "/opt/sbgrid/i386-mac/phenix/1.21rc1-5127/phenix-1.21rc1-5127/modules/cctbx_project/mmtbx/scaling/__init__.py", line 217, in show_plot
    print("", file=self.out)
ValueError: I/O operation on closed file
```

**Comment by bkpoon** [comment]
Thanks for you patience, I committed a fix and I can put in the 1.21.1 point release of Phenix.
